language: objective-c

osx_image: xcode9.2

rvm:
- 2.2

cache:
  directories:
    - ./Unity

before_install:
- chmod a+x ./Travis/install.sh

install:
- ./Travis/install.sh

before_script:
- chmod a+x ./Travis/build.sh

script:
- travis_wait 30 ./Travis/build.sh