language: objective-c

addons:
  sonarcloud:
    organization: "rafaelnsantos-github"

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh

install:
- ./Travis/install.sh

before_script:
- chmod a+x ./Travis/build.sh

script:
- sonar-scanner -Dsonar.projectKey=travis-unity -Dsonar.organization=rafaelnsantos-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
- ./Travis/build.sh

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  name: Travis-Unity $TRAVIS_TAG
  body: Automated release from Travis CI.
  file_glob: true
  file: /Build/webgl/*.zip
  skip_cleanup: true
  on:
    tags: true

  provider: pages
  skip-cleanup: true
  github-token: $GIT_TOKEN
  local-dir: ./Build/webgl/
  keep-history: true
  on:
    tags: true
