language: objective-c

addons:
  sonarcloud:
    organization: "rafaelnsantos-github"

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh
- chmod a+x ./Travis/build.sh

install:
- ./Travis/install.sh

script:
- sonar-scanner -Dsonar.projectKey=travis-unity -Dsonar.organization=rafaelnsantos-github -Dsonar.sources=. -Dsonar.language=cs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
- ./Travis/build.sh

deploy:
  - provider: releases
    api_key: $GIT_TOKEN
    file: 
    - ./Build/windows.zip
    - ./Build/mac.zip
    - ./Build/linux.zip
    skip_cleanup: true
    on:
      branch: master

  - provider: pages
    skip-cleanup: true
    github-token: $GIT_TOKEN
    local-dir: ./Build/webgl/
    keep-history: true
    on:
      branch: master