language: objective-c

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity
  - /Applications/Unity

before_install:
- chmod a+x ./Travis/install.sh

install:
- ./Travis/install.sh

before_script:
- chmod a+x ./Travis/build.sh

script:
- ./Travis/build.sh

# todo: fix this
# deploy:
#   provider: releases
#   api_key: $GIT_TOKEN
#   file:
#   - ./Build/windows/Travis-Unity.exe
#   - ./Build/osx/Travis-Unity.app
#   - ./Build/linux/Travis-Unity
#   skip_cleanup: true
#   on:
#     tags: true

  provider: pages
  skip-cleanup: true
  github-token: $GIT_TOKEN
  keep-history: true
  # local-dir: ./Build/webgl/Travis-Unity/
  local-dir: ./Build
  on:
    tags: true