language: objective-c

os: osx

rvm:
- 2.1.2

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh

install:
- ./Travis/install.sh

before_script:
- chmod a+x ./Travis/build.sh

script:
- ./Travis/build.sh