language: objective-c

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity
  - /Applications/Unity
  timeout: 1000

before_install:
- chmod a+x ./Travis/install.sh

install:
- ./Travis/install.sh

before_script:
- chmod a+x ./Travis/build.sh

script:
- ./Travis/build.sh

before_deploy:
- git config --local user.name "travisbot"
- git config --local user.email "travis-ci@org"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file:
  - ./Build/windows.zip
  - ./Build/mac.zip
  - ./Build/linux.zip
  skip_cleanup: true
  on:
    branch: master

  provider: pages
  skip-cleanup: true
  github-token: $GIT_TOKEN
  local-dir: ./Build/
  keep-history: true
  on:
    branch: master