language: objective-c

addons:
  sonarcloud:
    organization: "rafaelnsantos-github"

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh
- chmod a+x ./Travis/build.sh

install:
- ./Travis/install.sh

script:
- sonar-scanner -Dsonar.projectKey=travis-unity -Dsonar.organization=rafaelnsantos-github -Dsonar.sources=. -Dsonar.language=cs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
- ./Travis/build.sh

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: "true"
  file: /Build/webgl/*.zip
  skip_cleanup: true
  on:
    repo: rafaelnsantos/Travis-Unity
    branch: master
